odin_restful/odin_restful/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('sku_management.urls')),
    path('sku_management/', include('sku_management.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

odin_restful/sku_management/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('product/create/', views.ProductCreate.as_view(), name='product_create'),
    path('product/<int:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
    path('skus/', views.SKUListView.as_view(), name='skus'),
    path('sku/create/', views.SKUCreate.as_view(), name='sku_create'),
    path('sku/<int:pk>/update/', views.SKUUpdate.as_view(), name='sku_update'),
    path('sku/<int:pk>/delete/', views.SKUDelete.as_view(), name='sku_delete'),
    path('sku/<int:pk>', views.SKUDetailView.as_view(), name='sku-detail'),
]

odin_restful/sku_management/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class ModelWithTime(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Product(ModelWithTime):
    name = models.CharField(max_length=50)
    model = models.CharField(max_length=10)

    def get_absolute_url(self):
        return reverse('products')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-modified_at']

class SKU(ModelWithTime):
    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    test_plan_path = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse('skus')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-modified_at']

class TestConfig(ModelWithTime):
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class ManufacturingOrder(ModelWithTime):
    mo = models.CharField(max_length=100)
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE)

    def __str__(self):
        return self.mo

odin_restful/sku_management/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import SKU, Product


# Create your views here.
def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_skus=SKU.objects.all().count()

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_skus':num_skus, 'num_visits':num_visits},
    )

class ProductCreate(CreateView):
    model = Product
    fields = '__all__'
    #initial={'date_of_death':'05/01/2018',}

class ProductUpdate(UpdateView):
    model = Product
    fields = '__all__'

class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('products')

class ProductListView(generic.ListView):
    model = Product
    context_object_name = 'product_list'

class SKUCreate(CreateView):
    model = SKU
    fields = '__all__'
    #initial={'date_of_death':'05/01/2018',}

class SKUUpdate(UpdateView):
    model = SKU
    fields = '__all__'

class SKUDelete(DeleteView):
    model = SKU
    success_url = reverse_lazy('skus')
class SKUListView(generic.ListView):
    model = SKU
    context_object_name = 'sku_list'

class SKUDetailView(generic.DetailView):
    model = SKU

odin_restful/sku_management/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Odin</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'skus' %}">All SKUs</a></li>
            <li><a href="{% url 'products' %}">All Products</a></li>
            <br>
            {% if user.is_authenticated %}
              <li>Welcome {{ user.get_username }}</li>
              <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

odin_restful/sku_management/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <ul>
    <li><strong>SKUs:</strong> {{ num_skus }}</li>
  </ul>
  <p>fffYou have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

odin_restful/sku_management/templates/sku_management/product_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete {{ product.name }}</h1>

<p>Are you sure you want to delete the product: {{ product.name }} ({{ product.model }})?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

odin_restful/sku_management/templates/sku_management/product_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

odin_restful/sku_management/templates/sku_management/product_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Product List</h1>

    <a class="btn btn-primary" href="{% url 'product_create' %}" role="button">Add New Product</a>
    {% if product_list %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Model</th>
                    <th class="text-center">Action</th>
                    <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
            {% for product in product_list %}
                <tr>
                    <td class="col-md-1">{{forloop.counter}}</td>
                    <td>{{product.name}}</td>
                    <td>{{product.model}}</td>
                    <td class="text-center"><a href="{% url 'product_update' product.pk %}">Update</a> | <a href="{% url 'product_delete' product.pk %}">Delete</a></td>
                    <td>{{product.modified_at | date:"Y/m/d  H:m:s"}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
      <p>There are no sku in the database.</p>
    {% endif %}
{% endblock %}

odin_restful/sku_management/templates/sku_management/sku_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete {{ sku.name }}</h1>

<p>Are you sure you want to delete the product: {{ sku.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

odin_restful/sku_management/templates/sku_management/sku_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ sku.name }}</h1>
  <p><strong>Test Plan Path:</strong> {{ sku.test_plan_path }}</p>

  <div class="row">
    <div class="col-md-2">
        <h4>Test Configuration</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                {% for config in sku.testconfig_set.all %}
                <tr>
                    <td>{{config.name}}</td>
                    <td>{{config.value}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h4>MO List</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Number</th>
                </tr>
            </thead>
            <tbody>
                {% for mo in sku.manufacturingorder_set.all %}
                <tr>
                    <td>{{mo.mo}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
  </div>

{% endblock %}

odin_restful/sku_management/templates/sku_management/sku_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

odin_restful/sku_management/templates/sku_management/sku_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>SKU List</h1>
    <a class="btn btn-primary" href="{% url 'sku_create' %}" role="button">Add New SKU</a>
    {% if sku_list %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Product</th>
                    <th>Name</th>
                    <th class="text-center">Action</th>
                    <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
            {% for sku in sku_list %}
                <tr>
                    <td class="col-md-1">{{forloop.counter}}</td>
                    <td>{{sku.product}}</td>
                    <td><a href="{% url 'sku-detail' sku.pk %}">{{ sku.name }}</a></td>
                    <td class="text-center"><a href="{% url 'sku_update' sku.pk %}">Update</a> | <a href="{% url 'sku_delete' sku.pk %}">Delete</a></td>
                    <td>{{sku.modified_at | date:"Y/m/d  H:m:s"}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
      <p>There are no sku in the database.</p>
    {% endif %}
{% endblock %}